---

- hosts: media-server

  pre_tasks:
   - name: prefere ipv4 over ipv6 to fix DNS problem with secure.ubuntu
     become: yes
     lineinfile: dest="/etc/gai.conf" line="precedence ::ffff:0:0/96  100" state="present"

   - name: update apt cache
     become: yes
     apt: update_cache=yes
     changed_when: False

  roles:
    - sshd
    - file-server
    - video-disk-recorder
