---

   - name: apply all estuary settings
     xml: file={{ kodi_estuary_settings }} xpath=/settings/setting[@id='{{ item.id }}'] value={{ item.value }}
     with_items: "{{ kodi_skin_estuary_values }}"
