---

   - name: add xbmc repository
     become: yes
     apt_repository: repo="ppa:team-xbmc/ppa"
   - name: install kodi
     become: yes
     apt: name={{ item }} state=latest update_cache=yes
     with_items:
       - kodi
       - kodi-pvr-vdr-vnsi
     when: "ansible_distribution == 'Ubuntu'"
   - name: test if kodi base dir exists
     stat: path={{ kodi_base }}
     register: kodi_base_dir
     when: "ansible_distribution == 'Ubuntu'"
   - name: start kodi for the first time to create configuration folder
     shell: kodi
     async: 1
     poll: 0
     when: "ansible_distribution == 'Ubuntu' and kodi_base_dir.stat.exists == False"
