---

  - include: "kodi_install.yml"
  - include: "kodi_guisettings.yml"
  - include: "kodi_wol.yml"
  - include: "kodi_pvr_vdr_vnsi.yml"
  - include: "kodi_sources.yml"
  - include: "kodi_skin_estuary.yml"
