---

  - name: install requirements
    become: yes
    apt: name="libio-socket-ssl-perl"

  - name: install logitech media service
    become: yes
    apt: deb="{{ lookup('url', '{{ logitech_media_service_download_url }}') }}"
