---

  kodi_sources: "{{ kodi_base }}/userdata/sources.xml"
  kodi_database: "{{ kodi_base }}/userdata/Database"
  kodi_addon_data: "{{ kodi_base }}/userdata/addon_data"
  kodi_skin_estuary: "{{ kodi_addon_data }}/skin.estuary"

  kodi_channel_logos: "{{ kodi_base }}/channel_logos/"

  kodi_gui_settings_values:
    - { xpath: "/settings/locale/country", value: "Deutschland" }
    - { xpath: "/settings/locale/keyboardlayouts", value: "German QWERTZ" }
    - { xpath: "/settings/locale/language", value: "resource.language.de_de" }
    - { xpath: "/settings/locale/timezone", value: "Europe/Berlin" }
    - { xpath: "/settings/locale/timezonecountry", value: "Germany" }
    - { xpath: "/settings/general/settinglevel", value: 3 }
    - { xpath: "/settings/lookandfeel/soundskin", value: "" }
    - { xpath: "/settings/lookandfeel/skin", value: "skin.estuary" }
    - { xpath: "/settings/powermanagement/shutdowntime", value: 120 }
    - { xpath: "/settings/powermanagement/wakeonaccess", value: "true" }
    - { xpath: "/settings/pvrmenu/iconpath", value: "{{ kodi_channel_logos }}" }
    - { xpath: "/settings/musiclibrary/downloadinfo", value: "true" }
    - { xpath: "/settings/musiclibrary/overridetags", value: "true" }

  kodi_gui_settings_remove_default:
    - "/settings/locale/*/@default"
    - "/settings/general/*/@default"
    - "/settings/lookandfeel/*/@default"
    - "/settings/powermanagement/*/@default"
    - "/settings/pvrmanager/*/@default"
    - "/settings/pvrmenu/*/@default"

  kodi_vdr_port: "34890"
