---

 - name: add yavdr repositories
   become: yes
   apt_repository: repo="{{ item }}"
   with_items:
    - "ppa:yavdr/main"
    - "ppa:yavdr/stable-vdr"

 - name: install vdr
   become: yes
   apt: name="{{ item }}" state=latest
   with_items:
    - vdr
    - vdr-addon-acpiwakeup
    - vdr-addon-lifeguard
    - vdr-plugin-dummydevice
    - vdr-plugin-epgsearch
    - vdr-plugin-live
    - vdr-plugin-vnsiserver

 - name: enable vdr service
   become: yes
   lineinfile: dest="/etc/default/vdr" regexp="ENABLED" line="ENABLED=1"

 - name: enable ACPI wakeup
   become: yes
   lineinfile: dest="/etc/vdr/vdr-addon-acpiwakeup.conf" regexp="ACPI_ENABLED" line="ACPI_ENABLED=yes"

 - name: enable lifeguard for open samba file shares
   become: yes
   lineinfile: dest="/etc/vdr/lifeguard.conf" line="smb locks"

 - name: copy channel list
   become: yes
   copy: src="channels.conf" dest="/var/lib/vdr/channels.conf" owner="vdr" group="vdr" mode=0644

 - name: install german language support
   become: yes
   apt: name="{{ item }}" state=latest
   with_items:
    - "language-pack-de"
    - wngerman
    - wogerman
    - wswiss

 - name: make german default language
   become: yes
   copy: src="locale" dest="/etc/default/locale"
