---

 # install vdr

 - name: install vdr
   become: yes
   apt: name="{{ item }}" state=latest
   with_items:
    - vdr
    - vdr-plugin-epgsearch
    - vdr-plugin-live
    - vdr-plugin-vnsiserver

 # disable lirc

 - name: remove lirc package
   become: yes
   apt: name=lirc state=absent

 - name: null device for lirc
   become: yes
   lineinfile: dest="/etc/vdr/conf.d/00-vdr.conf" regexp="\-\-lirc" state="absent"

 # configure logging

 - name: log vdr messages into own logfile - configure rsyslog
   become: yes
   lineinfile: dest="/etc/vdr/conf.d/00-vdr.conf" regexp="\-\-log" line="--log=3.6"

 - name: log vdr messages into own logfile - configure rsyslog
   become: yes
   copy: src="30-vdr.conf" dest="/etc/rsyslog.d/30-vdr.conf"
   notify:
     - restart rsyslog

 - name: rotate vdr log files
   become: yes
   copy: src="logrotate_vdr" dest="/etc/logrotate.d/vdr"

 # configure vdr startup

 - name: enable vdr service
   become: yes
   lineinfile: dest="/etc/default/vdr" regexp="ENABLED" line="ENABLED=1"

 - name: run as root
   become: yes
   lineinfile: dest="/etc/vdr/conf.d/00-vdr.conf" regexp="\-\-user" line="--user=root"

 # system configure

 - name: install german language support
   become: yes
   apt: name="{{ item }}" state=latest
   with_items:
    - "language-pack-de"
    - wngerman
    - wogerman
    - wswiss

 - name: make german default language
   become: yes
   copy: src="locale" dest="/etc/default/locale"

 - name: set correct timezone
   become: yes
   timezone:
     name: "{{ system_timezone }}"

 # configure vdr settings

 - name: copy channel list
   become: yes
   copy: src="channels.conf" dest="/var/lib/vdr/channels.conf" owner="vdr" group="vdr" mode=0644

 - name: configure vdr
   become: yes
   lineinfile: dest="/etc/vdr/setup.conf" regexp="{{ item.key }}\ \=" line="{{ item.key }} = {{ item.value }}" create=yes
   with_items:
    - { key: "live.UserdefTimes", value: "20:15" }
    - { key: "live.UseStreamdev", value: "0"}
    - { key: "live.AdminPasswordMD5", value: "4:{{ vdr_live_password_hash }}" }
    - { key: "vnsiserver.Timeshift", value: "2"}
    - { key: "vnsiserver.TimeshiftBufferDir", value: "{{ vdr_timeshift_directory }}"}
    - { key: "vnsiserver.TimeshiftBufferFileSize", value: "20"}
    - { key: "vnsiserver.TimeshiftBufferSize", value: "20"}
    - { key: "UpdateChannels", value: "3" }
    - { key: "MarginStart", value: "1" }
    - { key: "MarginStop", value: "5" }
    - { key: "UseVps", value: "1" }
    - { key: "DefaultLifetime", value: "60" }
    - { key: "MaxVideoFileSize", value: "220000"}

 - name: configure vnsi allowed hosts
   become: yes
   template: src="vnsiserver_allowed_hosts.conf.j2" dest="/etc/vdr/plugins/vnsiserver/allowed_hosts.conf"

 # configure directories

 - name: ensure timeshift directory
   become: yes
   file: path="{{ vdr_timeshift_directory }}" state="directory" owner="vdr" group="vdr"

 - name: ensure recordings directory
   become: yes
   file: path="{{ vdr_recordings_directory }}" state="directory" owner="vdr" group="vdr"

 - name: use recordings directory
   become: yes
   lineinfile: dest="/etc/vdr/conf.d/00-vdr.conf" regexp="\-\-video" line="--video={{ vdr_recordings_directory }}"
