---

 # install vdr

 - name: add yavdr repositories
   become: yes
   apt_repository: repo="{{ item }}"
   with_items:
    - "ppa:yavdr/main"
    - "ppa:yavdr/stable-vdr"

 - name: install vdr
   become: yes
   apt: name="{{ item }}" state=latest
   with_items:
    - vdr
    - vdr-addon-acpiwakeup
    - vdr-addon-lifeguard
    - vdr-plugin-dummydevice
    - vdr-plugin-epgsearch
    - vdr-plugin-live
    - vdr-plugin-vnsiserver

 # configure service

 - name: enable vdr service
   become: yes
   lineinfile: dest="/etc/default/vdr" regexp="ENABLED" line="ENABLED=1"

 - name: enable ACPI wakeup
   become: yes
   lineinfile: dest="/etc/vdr/vdr-addon-acpiwakeup.conf" regexp="ACPI_ENABLED" line="ACPI_ENABLED=yes"

 - name: enable lifeguard for open samba file shares
   become: yes
   lineinfile: dest="/etc/vdr/lifeguard.conf" line="smb locks"

 # configure logging

 - name: log vdr messages into own logfile - configure rsyslog
   become: yes
   copy: src="30-vdr.conf" dest="/etc/rsyslog.d/30-vdr.conf"
   notify:
     - restart rsyslog

 - name: rotate vdr log files
   become: yes
   copy: src="logrotate_vdr" dest="/etc/logrotate.d/vdr"

 # configure user settings

 - name: copy channel list
   become: yes
   copy: src="channels.conf" dest="/var/lib/vdr/channels.conf" owner="vdr" group="vdr" mode=0644

 - name: install german language support
   become: yes
   apt: name="{{ item }}" state=latest
   with_items:
    - "language-pack-de"
    - wngerman
    - wogerman
    - wswiss

 - name: make german default language
   become: yes
   copy: src="locale" dest="/etc/default/locale"

 - name: configure vdr
   become: yes
   lineinfile: dest="/etc/vdr/setup.conf" regexp="{{ item.key }}" line="{{ item.key }} = {{ item.value }}" create=yes
   with_items:
    - { key: "live.UserdefTimes", value: "20:15" }
    - { key: "live.UseStreamdev", value: "0"}
    - { key: "live.AdminPasswordMD5", value: "4:{{ homeserver_vdr_live_password_hash }}" }
    - { key: "vnsiserver.TimeshiftBufferDir", value: "{{ vdr_timeshift_directory }}"}
    - { key: "UpdateChannels", value: "3" }
    - { key: "MarginStart", value: "1" }
    - { key: "MarginStop", value: "5" }
    - { key: "UseVps", value: "1" }

 - name: ensure timeshift directory
   become: yes
   file: path="{{ vdr_timeshift_directory }}" state="directory" owner="vdr" group="vdr"
