---

 - name: add yavdr repositories
   become: yes
   apt_repository: repo="{{ item }}"
   with_items:
    - "ppa:yavdr/main"
    - "ppa:yavdr/stable-vdr"

 - name: install vdr
   become: yes
   apt: name="{{ item }}" state=latest
   with_items:
    - vdr
    - vdr-addon-acpiwakeup
    - vdr-addon-lifeguard
    - vdr-plugin-dummydevice
    - vdr-plugin-epgsearch
    - vdr-plugin-live
    - vdr-plugin-vnsiserver

   notify:
     - restart vdr

 - name: enable vdr service
   become: yes
   lineinfile: dest="/etc/default/vdr" regexp="ENABLED" line="ENABLED=1"
   notify:
     - restart vdr

 - name: enable ACPI wakeup
   become: yes
   lineinfile: dest="/etc/vdr/vdr-addon-acpiwakeup.conf" regexp="ACPI_ENABLED" line="ACPI_ENABLED=yes"
   notify:
     - restart vdr

 - name: enable lifeguard for open samba file shares
   become: yes
   lineinfile: dest="/etc/vdr/lifeguard.conf" line="smb locks"
   notify:
     - restart vdr

 - name: copy channel list
   become: yes
   copy: src="channels.conf" dest="/var/lib/vdr/channels.conf" owner="vdr" group="vdr" mode=0644
   notify:
     - restart vdr
